service: xke-serverless-nodejs

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-1
  endpointType: regional

plugins:
  - serverless-plugin-typescript
  - serverless-offline # Run local API gateway


custom:
  stage: ${opt:stage, self:provider.stage, env:USER}
  # load key corresponding to the stage in the file or if key doesn't exist load "jpidev"
  perEnv: ${file(serverless-config.yml):${self:custom.stage}, file(serverless-config.yml):jpidev}

functions:

  books:
    handler: app/handlers/BookHandler.handler
    name: ${self:custom.stage}-xke-serverless-books
    memorySize: ${self:custom.perEnv.memory}
    timeout: 10
    environment:
      TABLE_BOOK: ${self:custom.stage}-book
    events:
      - http:
          path: /books
          method: ANY
      - http:
          path: /books/{any+}
          method: ANY


resources:
  Resources:
    BookTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Delete
      Properties:
        AttributeDefinitions:
          - AttributeName: 'id'
            AttributeType: 'S'
        KeySchema:
          - AttributeName: 'id'
            KeyType: 'HASH'
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.stage}-book
