service: xke-serverless-nodejs

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-1

plugins:
  # Run local API gateway
  - serverless-plugin-typescript
  - serverless-offline


custom:
  stage: ${opt:stage, self:provider.stage, env:USER}

functions:

  books:
    handler: app/handlers/BookHandler.handler
    name: xke-serverless-books-${self:custom.stage}
    events:
      - http:
          path: /
          method: GET
          cors: true
      - http:
          path: /{any+}
          method: ANY
          cors: true
