service: xke-serverless-nodejs

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-1

plugins:
  # Run local API gateway
  - serverless-offline

custom:
  stage: ${opt:stage, self:provider.stage, env:USER}

functions:

  book-list:
    handler: app/handlers/BookHandler.list
    name: xke-serverless-books-list-${self:custom.stage}
    events:
      - http:
          path: /books
          method: get

  book-get:
    handler: app/handlers/BookHandler.get
    name: xke-serverless-books-get-${self:custom.stage}
    events:
      - http:
          path: /books/{bookId}
          method: get
